### PR TITLE
OCaml 5.3 compatibility

### PR DESCRIPTION
**Pull request by phongulus**
Fix for OCaml 5.3, https://github.com/mjambon/tophide/issues/4

### CODE REVIEW

**Review by mjambon — APPROVED** [review]

**Comment by mjambon** [comment]
You might want to add a note about `Format_doc` and update the opam file with the dependency. I'm assuming it depends on the package [format-doc](https://github.com/Octachron/format-doc/blob/main/format-doc.opam).

**Comment by mjambon** [comment]
Feel free to merge anyway. Let me know if you maintainer rights.

**Comment by phongulus** [comment]
>it depends on the package [format-doc](https://github.com/Octachron/format-doc/blob/main/format-doc.opam).

No, `Format_doc` is from OCaml 5.3, here:
https://github.com/ocaml/ocaml/blob/70691e6d46c155f66bb5afb07357e01a48d33e59/utils/format_doc.mli

so there are no extra dependencies ☺️ . But we would need to put `"ocaml" {>= "5.3"} & {< "5.4"}` in the opam file.

@mjambon can you help merge? Then @kit-ty-kate can do the release.

**Comment by kit-ty-kate** [comment]
> Then maybe @kit-ty-kate can do the release?

I can't help doing the actual release (tagging) but i can help publishing to opam-repository if you want

**Comment by phongulus** [comment]
>i can help publishing to opam-repository if you want

Sorry, bad word choice, that's what I meant by "release" earlier 😅. Then for the tagging we'd need @mjambon.

**Comment by mjambon** [comment]
I pushed a tag `v1.1.0` and there's the GitHub-generated tarball at https://github.com/mjambon/tophide/tags. Is this good enough? (hoping the tarballs don't change too often)

**Comment by mjambon** [comment]
Actually, I downloaded GitHub's tarball and reuploaded it manually ("create release from tag" web interface). This should solve checksum issues.

**Comment by kit-ty-kate** [comment]
Thanks, i've opened a PR to publish the release in opam-repository in https://github.com/ocaml/opam-repository/pull/26769

**Pull request merged**
